-- Initial schema

-- Versionning
CREATE TABLE DBVERSION (
  VALUE INTEGER NOT NULL,
  UPDATED TIMESTAMP NOT NULL
);

-- Configuration table
CREATE TABLE CONFIGURATION (
	NAME VARCHAR(40) NOT NULL,
	VALUE VARCHAR(200) NOT NULL,
	CONSTRAINT PK_CONFIGURATION PRIMARY KEY (NAME)
);

-- Pipeline
CREATE TABLE PIPELINE (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(80) NOT NULL,
  DESCRIPTION VARCHAR(1000) NULL,
  CONSTRAINT PK_PIPELINE PRIMARY KEY (ID),
  CONSTRAINT UQ_PIPELINE UNIQUE (NAME)
);
