-- Initial schema

-- Versionning
CREATE TABLE DBVERSION (
  VALUE INTEGER NOT NULL,
  UPDATED TIMESTAMP NOT NULL
);

-- Pipeline
CREATE TABLE PIPELINE (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(80) NOT NULL,
  DESCRIPTION VARCHAR(1000) NULL,
  CONSTRAINT PK_PIPELINE PRIMARY KEY (ID),
  CONSTRAINT UQ_PIPELINE UNIQUE (NAME)
);